 @BASE_URL = http://localhost:3000


###
GET {{BASE_URL}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJUeXBlIjoiMCIsIl9pZCI6IjVmODdmY2ZhNmMwZTU3NTgzY2UwMjhhMSIsIm5hbWUiOiJtZWN6dXBLYXltYWthbSIsInVzZXJOYW1lIjoiZGVsaWtheW1ha2FtIiwiZW1haWwiOiJkZWxpLmtheW1ha2FtQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDUwdjh3QlVIL0w3UGp6cXc0TThicWVSQVlPREpBUzFmUC9XSXBQbTVCY0c4dDhnZjc2YVBtIiwiY3JlYXRlZEF0IjoiMjAyMC0xMC0xNVQwNzo0MDo0Mi4zNDFaIiwidXBkYXRlZEF0IjoiMjAyMC0xMC0xNVQwNzo0MDo0Mi4zNDFaIiwiX192IjowfSwiaWF0IjoxNjAyNzU1ODY4LCJleHAiOjE2MDI3NjMwNjh9.HcdK06v42ed3Kwdzy84nJc_yuMIWMYrg3q3RUR91OCA


###
POST {{BASE_URL}}/user/generate-membership-token
Content-Type: application/json

{
    "email" : "enes.eknc.96@gmail.com"
}

###
POST {{BASE_URL}}/user/check-membership-token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiZW5lcy5la25jLjk2QGdtYWlsLmNvbSJ9LCJpYXQiOjE2MTcwMTkzOTEsImV4cCI6MTYxNzI3ODU5MX0.xSxUeZbNKJW2Hyjs69IxyfGaue2JFc9wCkUtAR_xmMg"
}

###
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "name":"enes ekinci",
    "username":"enesekinci",
    "email": "enes.eknc.96@gmail.com",
    "password":"password"
}

###
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "username":"enesekinci",
    "email": "enes.eknc.96@gmail.com",
    "password":"password"
}

###
POST {{BASE_URL}}/user/update-me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWUiOiJlbmVzIGVraW5jaSIsImVtYWlsIjoiZW5lcy5la25jLjk2QGdtYWlsLmNvbSJ9LCJpYXQiOjE2MTcwNDk2NjMsImV4cCI6MTYxNzEzNjA2M30.ab7JXq1VnfqEeDb93OSTruzXo4OOTF-tmcqPoaGpeLU


{
    "name":"enes ekinci",
    "username":"enesekinci",
    "email": "enes.eknc.96@gmail.com",
    "password":"password"
}